### ISSUE TITLE
A section itself cannot be opened

### ISSUE THREAD

**Issue by pravic** [aturon/apr#1]
https://aturon.github.io/apr/
Click on [Task and executors](https://aturon.github.io/apr/task-model/_chapter.html) - 404, although `_chapter.md` files exist in sources.

Isn't chapter should be named as a `index.md`, according to mdBook [example](https://github.com/rust-lang-nursery/mdBook/tree/master/book-example/src/for_developers)?

**Comment by huangjj27** [comment]
I found the same problem in my Chinese translation. I'll try if index.md is the proper name.

**Comment by Michael-F-Bryan** [comment]
I'm just looking into the issue and it seems really strange. If you look at your repo's `gh-pages` branch (which is served by GitHub Pages as-is), you can see that mdbook has rendered the chapter and saved it as `whatever/_chapter.html`. So by all means, GitHub Pages *should* be serving up that page.

**Comment by huangjj27** [comment]
checked by [new rendered](https://aturon.github.io/apr/async-in-rust/chapter.html). The issue should be closed.

**Comment by pravic** [comment]
Yes, it is fixed now.
